[package]
name = "csvtool"
description = "deal with CSV files"
license = "MIT"
repository = "https://github.com/patrickbucher/csvtool"
version = "0.0.4"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
csv = "1.3.0"
regex = "1.10.4"
